FROM rocker/r-ver:4.5.0

# Generated by the vetiver package; edit with care

RUN useradd --create-home appuser
ENV RENV_CONFIG_REPOS_OVERRIDE https://packagemanager.rstudio.com/cran/latest
ENV HOME=/home/appuser
WORKDIR $HOME

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
  libcurl4-openssl-dev \
  libicu-dev \
  libsodium-dev \
  libssl-dev \
  libx11-dev \
  libgomp1 \
  make \
  zlib1g-dev \
  && apt-get clean

COPY vetiver_renv.lock renv.lock
RUN Rscript -e "install.packages('renv')"
RUN Rscript -e "renv::restore()"

# Install bundle package explicitly if not in renv.lock
RUN Rscript -e "if (!require('bundle', quietly = TRUE)) install.packages('bundle')"

# Copy model files and plumber script with proper permissions
COPY --chown=appuser:appuser my-pins /opt/ml/my-pins
COPY --chown=appuser:appuser plumber.R /opt/ml/plumber.R

# Switch to appuser BEFORE creating directories
USER appuser

# Create directories with proper ownership
RUN mkdir -p /tmp

EXPOSE 7860
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb('/opt/ml/plumber.R'); pr$run(host = '0.0.0.0', port = 7860)"]